# Generated by Django 3.1 on 2020-08-20 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30)),
                ('autor', models.CharField(max_length=30)),
                ('titulo', models.CharField(max_length=30)),
                ('anio', models.IntegerField()),
                ('status', models.CharField(choices=[('li', 'Libre'), ('pt', 'Prestado')], default='LI', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('correo', models.CharField(max_length=30)),
                ('telefono', models.CharField(max_length=30)),
                ('numLibros', models.IntegerField()),
                ('adeudo', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Bibloteca.persona')),
                ('matricula', models.IntegerField()),
            ],
            bases=('Bibloteca.persona',),
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Bibloteca.persona')),
                ('numEmpleado', models.IntegerField()),
            ],
            bases=('Bibloteca.persona',),
        ),
        migrations.CreateModel(
            name='Revista',
            fields=[
                ('material_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Bibloteca.material')),
            ],
            bases=('Bibloteca.material',),
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30)),
                ('fechaSalida', models.DateField()),
                ('fechaRegreso', models.DateField()),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bibloteca.material')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bibloteca.persona')),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('material_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Bibloteca.material')),
                ('fotoPortada', models.ImageField(blank=True, upload_to='portadas/')),
                ('editorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bibloteca.editorial')),
            ],
            bases=('Bibloteca.material',),
        ),
    ]
