# Generated by Django 3.1 on 2020-08-26 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bibloteca', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='numLibros',
            new_name='num_libros',
        ),
        migrations.RenameField(
            model_name='profesor',
            old_name='numEmpleado',
            new_name='num_empleado',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='fotoPortada',
        ),
        migrations.AddField(
            model_name='libro',
            name='foto_portada',
            field=models.ImageField(blank=True, upload_to='imagenes/'),
        ),
        migrations.AlterField(
            model_name='material',
            name='status',
            field=models.CharField(choices=[('li', 'Libre'), ('pt', 'Prestado')], default='li', max_length=2),
        ),
        migrations.AlterField(
            model_name='persona',
            name='correo',
            field=models.EmailField(max_length=254, verbose_name=''),
        ),
    ]
