# Generated by Django 3.1 on 2020-08-26 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bibloteca', '0002_auto_20200826_2342'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prestamo',
            old_name='fechaRegreso',
            new_name='fecha_regreso',
        ),
        migrations.RenameField(
            model_name='prestamo',
            old_name='fechaSalida',
            new_name='fecha_salida',
        ),
    ]
